name: Run big tester
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run big tester.sh
      run: |
        make
        bash ./tester.sh vm
